oro_menu_config:
    items:
        reports_tab:
            label: Reports & Segments
            uri: '#'

        segments_divider:
            class: divider

        manage_segments:
            label: 'Manage Segments'
            route: 'oro_segment_index'
            extras:
                position: 100
                routes: ['oro_segment_*']

    tree:
        application_menu:
            children:
                reports_tab:
                    children:
                        segments_divider: ~
                        manage_segments: ~

oro_titles:
    oro_segment_index:  ~
    oro_segment_view:   %%segment.name%% - Segments
    oro_segment_create: Create segment
    oro_segment_update: %%segment.name%% - Edit
