parameters:
#    oro_segment.example.class: Oro\Bundle\SegmentBundle\Example

services:
#    oro_segment.example:
#        class: %oro_segment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
