parameters:
    oro_segment.segment.entity.class:                        Oro\Bundle\SegmentBundle\Entity\Segment
    oro_segment.segment_manager.class:                       Oro\Bundle\SegmentBundle\Entity\Manager\SegmentManager
    oro_segment.segment_manager.api.class:                   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_segment.listener.navigation_listener.class:          Oro\Bundle\SegmentBundle\EventListener\NavigationListener
    oro_segment.datagrid.configuration.provider.class:       Oro\Bundle\SegmentBundle\Grid\ConfigurationProvider

services:
    oro_segment.entity_provider:
        alias: oro_entity.entity_provider

    oro_segment.segment_manager:
        class: %oro_segment.segment_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    oro_segment.segment_manager.api:
        class: %oro_segment.segment_manager.api.class%
        arguments:
            - %oro_segment.segment.entity.class%
            - @doctrine.orm.entity_manager

    oro_segment.listener.navigation_listener:
        class: %oro_segment.listener.navigation_listener.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_entity_config.provider.entity
            - @oro_security.security_facade
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    oro_segment.datagrid.configuration.provider:
        class: %oro_segment.datagrid.configuration.provider.class%
        arguments:
            - @oro_query_designer.query_designer.manager
            - @doctrine
        tags:
            - { name: oro_datagrid.configuration.provider }
