parameters:
    oro_segment.segment.entity.class:                        Oro\Bundle\SegmentBundle\Entity\Segment
    oro_segment.segment_manager.class:                       Oro\Bundle\SegmentBundle\Entity\Manager\SegmentManager
    oro_segment.segment_manager.api.class:                   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_segment.datagrid.configuration.provider.class:       Oro\Bundle\SegmentBundle\Grid\ConfigurationProvider
    oro_segment.filter.segment.class:                        Oro\Bundle\SegmentBundle\Filter\SegmentFilter

services:
    oro_segment.entity_provider:
        alias: oro_entity.entity_provider

    oro_segment.segment_manager:
        class: %oro_segment.segment_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    oro_segment.segment_manager.api:
        class: %oro_segment.segment_manager.api.class%
        arguments:
            - %oro_segment.segment.entity.class%
            - @doctrine.orm.entity_manager

    oro_segment.datagrid.configuration.provider:
        class: %oro_segment.datagrid.configuration.provider.class%
        arguments:
            - @oro_query_designer.query_designer.manager
            - @doctrine
        tags:
            - { name: oro_datagrid.configuration.provider }

    oro_segment.filter.segment:
        class: %oro_segment.filter.segment.class%
        arguments:
            - @form.factory
            - @oro_filter.filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: segment }
